spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/skylon
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/skylon
    locations: filesystem:db/migrations
    enabled: true

application:
  security:
    jwt:
      secret: secret-key
      access-token-expiration-sec: 1 #600
      refresh-token-expiration-sec: 1 #604800
    password-encoder:
      strength: 10
